refactor os image generation, import in Ashburn
Signed-off-by: Koray Oksay <koray.oksay@gmail.com>

diff --git a/.github/workflows/periodic-build-new-actions-arm-vm.yml b/.github/workflows/periodic-build-new-actions-arm-vm.yml
--- a/.github/workflows/periodic-build-new-actions-arm-vm.yml
+++ b/.github/workflows/periodic-build-new-actions-arm-vm.yml
@@ -8,6 +8,14 @@ permissions:
   actions: read
   contents: read
 
+env:
+  OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
+  OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
+  OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
+  OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
+  OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
+  COMPARTMENT_ID: ocid1.compartment.oc1..aaaaaaaa22icap66vxktktubjlhf6oxvfhev6n7udgje2chahyrtq65ga63a
+
 jobs:
   build:
     name: Build new Actions ARM VM
@@ -34,16 +42,10 @@ jobs:
 
       - name: Check latest release
         id: check_latest
-        env:
-          OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
-          OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
-          OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
-          OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
-          OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
         run: |
           set -euo pipefail
           LATEST_RELEASE=$(curl -fsSL "https://api.github.com/repos/actions/runner-images/releases?per_page=100" | jq -r '.[] | select(.prerelease == false) | select(.name | startswith("Ubuntu 24.04")) | .tag_name' | head -1)
-          IMAGE_EXISTS=$(oci compute image list --compartment-id ocid1.compartment.oc1..aaaaaaaa22icap66vxktktubjlhf6oxvfhev6n7udgje2chahyrtq65ga63a --operating-system "ubuntu-24.04-arm64-gha-image" --operating-system-version ${LATEST_RELEASE})
+          IMAGE_EXISTS=$(oci compute image list --compartment-id ${{ env.COMPARTMENT_ID }} --operating-system "ubuntu-24.04-arm64-gha-image" --operating-system-version ${LATEST_RELEASE})
           if [ -z "$IMAGE_EXISTS" ]; then
             echo "image_exists=false" >> "$GITHUB_OUTPUT"
           else
@@ -52,12 +54,6 @@ jobs:
 
       - name: Create Arm64 BareMetal Instance
         if: steps.check_latest.outputs.image_exists == 'false'
-        env:
-          OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
-          OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
-          OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
-          OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
-          OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
         run: |
           ${{ github.workspace }}/.github/scripts/create_bare_metal.sh
           cat ${{ github.workspace }}/.env >> $GITHUB_ENV
@@ -66,12 +62,6 @@ jobs:
       - name: Build VM Image
         if: steps.check_latest.outputs.image_exists == 'false'
         id: build_image
-        env:
-          OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
-          OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
-          OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
-          OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
-          OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
         run: |
           set -euo pipefail
           CREDS_FILE=$(mktemp)
@@ -87,6 +77,8 @@ jobs:
           shred -u "$CREDS_FILE"
           ssh -o ServerAliveInterval=60 -i ${{ github.workspace }}/id_rsa ubuntu@$PUBLIC_IP -- ./build_arm_image.sh
           scp -i ${{ github.workspace }}/id_rsa ubuntu@$PUBLIC_IP:/tmp/image_ocid .
+          scp -i ${{ github.workspace }}/id_rsa ubuntu@$PUBLIC_IP:/tmp/object_name .
+          scp -i ${{ github.workspace }}/id_rsa ubuntu@$PUBLIC_IP:/tmp/image_tag .
         shell: bash
 
       - name: Upload image OCID
@@ -96,14 +88,22 @@ jobs:
           name: image-ocid
           path: ./image_ocid
 
+      - name: Upload object name
+        if: steps.check_latest.outputs.image_exists == 'false'
+        uses: actions/upload-artifact@v7
+        with:
+          name: object-name
+          path: ./object_name
+
+      - name: Upload image tag
+        if: steps.check_latest.outputs.image_exists == 'false'
+        uses: actions/upload-artifact@v7
+        with:
+          name: image-tag
+          path: ./image_tag
+
       - name: Terminate Arm64 BareMetal Instance
         if: always()
-        env:
-          OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
-          OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
-          OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
-          OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
-          OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
         run: |
           set -euo pipefail
           if [ -n "${INSTANCE_OCID:-}" ]; then
@@ -233,12 +233,6 @@ jobs:
   release-new-image:
     runs-on: ubuntu-latest
     needs: [run-kind-with-arc, test-runner]
-    env:
-      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
-      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
-      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
-      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
-      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
     steps:
       - name: Download image OCID
         uses: actions/download-artifact@v8
@@ -255,3 +249,70 @@ jobs:
         run: |
           IMAGE_ID=$(cat image_ocid)
           oci compute image update --image-id ${IMAGE_ID} --operating-system ubuntu-24.04-arm64-gha-image --display-name ubuntu-24.04-arm64-gha-image
+
+  import-image-ashburn:
+    runs-on: ubuntu-latest
+    needs: release-new-image
+    env:
+      OS_NAME: ubuntu-24.04-arm64-gha-image
+      BUCKET_NAMESPACE: axtwf1hkrwcy
+      BUCKET_NAME: bucket-20250428-1925
+      REGION: us-ashburn-1
+    steps:
+      - name: Download image OCID
+        uses: actions/download-artifact@v8
+        with:
+          name: object-name
+
+      - name: Download image tag
+        uses: actions/download-artifact@v8
+        with:
+          name: image-tag
+
+      - name: Install OCI CLI
+        uses: actions/setup-python@v6
+        with:
+          python-version: '3.13'
+          pip-install: oci-cli
+
+      - name: Import Custom Image on Ashburn
+        run: |
+          OBJECT_NAME=$(cat object_name)
+          IMAGE_TAG=$(cat image_tag)
+          IMAGE_ID=$(oci compute image import from-object \
+            --bucket-name ${{ env.BUCKET_NAME }} \
+            --compartment-id ${{ env.COMPARTMENT_ID }} \
+            --namespace ${{ env.BUCKET_NAMESPACE }} \
+            --operating-system ${{ env.OS_NAME }} \
+            --display-name ${{ env.OS_NAME }} \
+            --name ${OBJECT_NAME} \
+            --operating-system-version ${IMAGE_TAG} \
+            --launch-mode PARAVIRTUALIZED \
+            --region ${{ env.REGION }} \
+            --query 'data.id' --raw-output)
+          while true; do
+            STATUS=$(oci compute image get --image-id ${IMAGE_ID} --region ${{ env.REGION }} --query 'data."lifecycle-state"' --raw-output)
+            echo "Image import status: $STATUS"
+            if [ "$STATUS" == "AVAILABLE" ]; then
+              echo "Image import completed"
+              break
+            elif [ "$STATUS" == "FAILED" ]; then
+              echo "Image import failed"
+              exit 1
+            else
+              echo "Waiting for image import to complete..."
+              sleep 30
+            fi
+          done
+
+      - name: Enable VM.Standard.A1.Flex in Ashburn
+        run: |
+          oci raw-request --http-method PUT \
+            --target-uri https://iaas.us-ashburn-1.oraclecloud.com/20160918/images/${IMAGE_ID}/shapes/VM.Standard.A1.Flex \
+            --request-body "{\"imageId\":\"${IMAGE_ID}\",\"shape\":\"VM.Standard.A1.Flex\"}"
+
+      - name: Update Capabilities of the image
+        run: |
+          oci raw-request --http-method POST \
+            --target-uri https://iaas.us-ashburn-1.oraclecloud.com/20160918/computeImageCapabilitySchemas \
+            --request-body "{\"schemaData\":{\"Compute.Firmware\":{\"values\":[\"BIOS\",\"UEFI_64\"],\"defaultValue\":\"UEFI_64\",\"source\":\"IMAGE\",\"descriptorType\":\"enumstring\"},\"Compute.LaunchMode\":{\"values\":[\"PARAVIRTUALIZED\"],\"defaultValue\":\"PARAVIRTUALIZED\",\"source\":\"IMAGE\",\"descriptorType\":\"enumstring\"},\"Compute.AMD_SecureEncryptedVirtualization\":{\"defaultValue\":\"false\",\"source\":\"IMAGE\",\"descriptorType\":\"boolean\"},\"Compute.SecureBoot\":{\"defaultValue\":\"false\",\"source\":\"IMAGE\",\"descriptorType\":\"boolean\"},\"Network.AttachmentType\":{\"values\":[\"PARAVIRTUALIZED\"],\"defaultValue\":\"PARAVIRTUALIZED\",\"source\":\"IMAGE\",\"descriptorType\":\"enumstring\"},\"Network.IPv6Only\":{\"defaultValue\":\"false\",\"source\":\"IMAGE\",\"descriptorType\":\"boolean\"},\"Storage.BootVolumeType\":{\"values\":[\"ISCSI\",\"PARAVIRTUALIZED\"],\"defaultValue\":\"PARAVIRTUALIZED\",\"source\":\"IMAGE\",\"descriptorType\":\"enumstring\"},\"Storage.LocalDataVolumeType\":{\"values\":[\"ISCSI\",\"PARAVIRTUALIZED\"],\"defaultValue\":\"PARAVIRTUALIZED\",\"source\":\"IMAGE\",\"descriptorType\":\"enumstring\"},\"Storage.RemoteDataVolumeType\":{\"values\":[\"ISCSI\",\"PARAVIRTUALIZED\"],\"defaultValue\":\"PARAVIRTUALIZED\",\"source\":\"IMAGE\",\"descriptorType\":\"enumstring\"},\"Storage.ConsistentVolumeNaming\":{\"defaultValue\":\"true\",\"source\":\"IMAGE\",\"descriptorType\":\"boolean\"},\"Storage.Iscsi.MultipathDeviceSupported\":{\"defaultValue\":\"false\",\"source\":\"IMAGE\",\"descriptorType\":\"boolean\"},\"Storage.ParaVirtualization.EncryptionInTransit\":{\"defaultValue\":\"true\",\"source\":\"IMAGE\",\"descriptorType\":\"boolean\"},\"Storage.ParaVirtualization.AttachmentVersion\":{\"values\":[\"1\",\"2\"],\"defaultValue\":\"2\",\"source\":\"IMAGE\",\"descriptorType\":\"enuminteger\"}},\"imageId\":\"${IMAGE_ID}\",\"compartmentId\":\"${COMPARTMENT_ID}\",\"computeGlobalImageCapabilitySchemaVersionName\":\"34dd2cea-aff2-4f45-b8f6-1cb5290bfab2\"}"
diff --git a/.github/workflows/periodic-build-new-actions-vm.yml b/.github/workflows/periodic-build-new-actions-vm.yml
--- a/.github/workflows/periodic-build-new-actions-vm.yml
+++ b/.github/workflows/periodic-build-new-actions-vm.yml
@@ -8,6 +8,14 @@ permissions:
   actions: read
   contents: read
 
+env:
+  OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
+  OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
+  OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
+  OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
+  OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
+  COMPARTMENT_ID: ocid1.compartment.oc1..aaaaaaaa22icap66vxktktubjlhf6oxvfhev6n7udgje2chahyrtq65ga63a
+
 jobs:
   build:
     name: Build new Actions VM
@@ -35,26 +43,14 @@ jobs:
           pip-install: oci-cli
 
       - name: Verify OCI CLI
-        env:
-          OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
-          OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
-          OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
-          OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
-          OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
-        run: oci compute image list --compartment-id ocid1.compartment.oc1..aaaaaaaa22icap66vxktktubjlhf6oxvfhev6n7udgje2chahyrtq65ga63a --operating-system runner-images --operating-system-version 123456
+        run: oci compute image list --compartment-id ${{ env.COMPARTMENT_ID }} --operating-system runner-images --operating-system-version 123456
 
       - name: Check latest release
         id: check_latest
-        env:
-          OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
-          OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
-          OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
-          OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT  }}
-          OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
         run: |
           set -euo pipefail
           LATEST_RELEASE=$(curl -fsSL "https://api.github.com/repos/actions/runner-images/releases?per_page=100" | jq -r '.[] | select(.prerelease == false) | select(.name | startswith("Ubuntu 24.04")) | .tag_name' | head -1)
-          IMAGE_EXISTS=$(oci compute image list --compartment-id ocid1.compartment.oc1..aaaaaaaa22icap66vxktktubjlhf6oxvfhev6n7udgje2chahyrtq65ga63a --operating-system "ubuntu-24.04-amd64-gha-image" --operating-system-version ${LATEST_RELEASE})
+          IMAGE_EXISTS=$(oci compute image list --compartment-id ${{ env.COMPARTMENT_ID }} --operating-system "ubuntu-24.04-amd64-gha-image" --operating-system-version ${LATEST_RELEASE})
           if [ -z "$IMAGE_EXISTS" ]; then
             echo "image_exists=false" >> "$GITHUB_OUTPUT"
           else
@@ -126,6 +122,18 @@ jobs:
         with:
           name: image-ocid
           path: /tmp/image_ocid
+
+      - name: Upload object name
+        uses: actions/upload-artifact@v7
+        with:
+          name: object-name
+          path: /tmp/object_name
+
+      - name: Upload image tag
+        uses: actions/upload-artifact@v7
+        with:
+          name: image-tag
+          path: /tmp/image_tag
 
   run-kind-with-arc:
     runs-on: ubuntu-latest
@@ -248,11 +256,7 @@ jobs:
     runs-on: ubuntu-latest
     needs: [run-kind-with-arc, test-runner]
     env:
-      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
-      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
-      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
-      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
-      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
+      OS_NAME: ubuntu-24.04-amd64-gha-image
     steps:
       - name: Download image OCID
         uses: actions/download-artifact@v8
@@ -268,4 +272,68 @@ jobs:
       - name: Release
         run: |
           IMAGE_ID=$(cat image_ocid)
-          oci compute image update --image-id ${IMAGE_ID} --operating-system ubuntu-24.04-amd64-gha-image --display-name ubuntu-24.04-amd64-gha-image
+          oci compute image update --image-id ${IMAGE_ID} --operating-system ${{ env.OS_NAME }} --display-name ${{ env.OS_NAME }}
+
+  import-image-ashburn:
+    runs-on: ubuntu-latest
+    needs: release-new-image
+    env:
+      OS_NAME: ubuntu-24.04-amd64-gha-image
+      BUCKET_NAMESPACE: axtwf1hkrwcy
+      BUCKET_NAME: bucket-20250428-1925
+      REGION: us-ashburn-1
+    steps:
+      - name: Download image OCID
+        uses: actions/download-artifact@v8
+        with:
+          name: object-name
+
+      - name: Download image tag
+        uses: actions/download-artifact@v8
+        with:
+          name: image-tag
+
+      - name: Install OCI CLI
+        uses: actions/setup-python@v6
+        with:
+          python-version: '3.13'
+          pip-install: oci-cli
+
+      - name: Import Custom Image on Ashburn
+        run: |
+          OBJECT_NAME=$(cat object_name)
+          IMAGE_TAG=$(cat image_tag)
+          IMAGE_ID=$(oci compute image import from-object \
+            --bucket-name ${{ env.BUCKET_NAME }} \
+            --compartment-id ${{ env.COMPARTMENT_ID }} \
+            --namespace ${{ env.BUCKET_NAMESPACE }} \
+            --operating-system ${{ env.OS_NAME }} \
+            --display-name ${{ env.OS_NAME }} \
+            --name ${OBJECT_NAME} \
+            --operating-system-version ${IMAGE_TAG} \
+            --launch-mode PARAVIRTUALIZED \
+            --region ${{ env.REGION }} \
+            --query 'data.id' --raw-output)
+          while true; do
+            STATUS=$(oci compute image get --image-id ${IMAGE_ID} --region ${{ env.REGION }} --query 'data."lifecycle-state"' --raw-output)
+            echo "Image import status: $STATUS"
+            if [ "$STATUS" == "AVAILABLE" ]; then
+              echo "Image import completed"
+              break
+            elif [ "$STATUS" == "FAILED" ]; then
+              echo "Image import failed"
+              exit 1
+            else
+              echo "Waiting for image import to complete..."
+              sleep 30
+            fi
+          done
+
+      - name: Enable A10 shapes on Ashburn
+        run: |
+          oci raw-request --http-method PUT \
+            --target-uri https://iaas.us-ashburn-1.oraclecloud.com/20160918/images/${IMAGE_ID}/shapes/VM.GPU.A10.1 \
+            --request-body "{\"imageId\":\"${IMAGE_ID}\",\"shape\":\"VM.GPU.A10.1\"}"
+          oci raw-request --http-method PUT \
+            --target-uri https://iaas.us-ashburn-1.oraclecloud.com/20160918/images/${IMAGE_ID}/shapes/VM.GPU.A10.2 \
+            --request-body "{\"imageId\":\"${IMAGE_ID}\",\"shape\":\"VM.GPU.A10.2\"}"
